### PR TITLE
Updated registry version to 3 for all appliances

### PR DESCRIPTION
**Pull request by adosztal**
Just some maintenance work...

### CODE REVIEW

**Comment by ehlers** [comment]
Maybe alpine-linux.gns3a can be downgraded from registry version 4 to 3. I don't see any requirements for registry version 4.

When using version 3 then users still using v1.5 can use the alpine appliance.

**Comment by adosztal** [comment]
I don't know why Alpine is v4. @noplay?

Yes, v3 is compatible with 1.5. As I see the old templates were updated with new fields that are not supported in v1/2 but their version number was left.

I think the best is to have a common baseline now and make sure we won't forget to update this property in the future.

**Comment by ehlers** [comment]
As GNS3 v1.4 (the first version, that supports appliances) is really out of date, I agree, that GNS3 v1.5 (registry version 3) is a good minimal version, that we should support.

There are two current appliances, that need version 4, see issue https://github.com/GNS3/gns3-registry/issues/234. I suggest, that an appliance is tested against the schema version of its registry_version field. That way we will notice, when an appliance uses a registry version, that's too low.

**Comment by noplay** [comment]
I agree we should improve the check schema to better detect the correct schema version

**Comment by noplay** [comment]
I will make a PR for that

**Comment by noplay** [comment]
PR with a tool for checking open. 

It seem we need v4 for alpine due to the way we reference the docker image.

**Comment by ehlers** [comment]
Just changed the registry_version in alpine-linux.gns3a to 3 and tried to import it in GNS3 v1.5.4.
Works fine, no issues during import and use of that appliance.

**Comment by adosztal** [comment]
This must be because v4 only makes the tag mandatory but it doesn't mean that v3 rejects the image if there's a tag in the string.

**Comment by ehlers** [comment]
Andrew is right, v3 allows images with tag, see this part from appliance.json from GNS3 GUI v1.5:
```
            "image": {
                "type": "string",
                "title": "Docker image in the Docker Hub"
            },
```

But anyway, the docker image in alpine-linux.gns3a doesn't contain a tag.

And since fddde6574a46904f709ecb89c5bea383de6bbecf v4 drops the requirement of a tag in docker images.

**Comment by adosztal** [comment]
The Travis check already spotted this is #235. :)
@noplay, if you merge this, I think that one will turn green too.

**Comment by noplay** [comment]
I fixed an issue with NXOS it need to be version 4

**Pull request merged**
