### PR TITLE
General purpose Alpine-based endhost.

### PR DESCRIPTION
**Pull request by AJNOURI**
I included the following tools: openssh, mtr, nmap, iperf, socat, vim, nano, curl, links, iputils, rsync, bash.
The resulting image is 54.44 MB size.
The list can grow and users can use the TUI script [https://github.com/AJNOURI/Alpine_Image_Builder](https://github.com/AJNOURI/Alpine_Image_Builder) to build own image flavors.

### CODE REVIEW

**Comment by noplay** [comment]
I need to test. But dig is installed? I try to think what could be usefull, perhaps we could make a volume to host the content of /home/user in order to keep stuff like SSH keys between reboot.

**Comment by AJNOURI** [comment]
Added bind-tools for dig and a script to start sshd, the user can connect to ssh with password "gns3" and can also exchange public keys for passwordless connections.
I mapped /root/.ssh and /etc/ssh for SSH and /data for any other user data.

**Comment by noplay** [comment]
Added to the docker hub

**Comment by AJNOURI** [comment]
Thanks Julien.

**Pull request merged**
