### PR TITLE
add Huawei appliances and symbols

### PR DESCRIPTION
**Pull request by mininetworks**
Before submitting a pull request, please check the following.

---
When updating an **existing** appliance:
- [ ] The new version is on top.
- [ ] The filenames in the "images" section are unique, to avoid appliances / version overwriting each other.
- [ ] If you forked the repo, running check.py doesn't drop any errors for the updated file.
---
When creating a **new** appliance:
- It's tested locally, i.e.
  - [x] You dragged an instance into a project on your box, got it installed (if necessary), and did some basic network checks (ping, UI reachable, etc.).
  - [x] GNS3 VM can run it without any tweaks.
  - [x] The device is in the right category: router, switch, guest (hosts), firewall
  - [x] You filled in as much info as possible (checks the schemas and other appliance files for some guidance).
- [ ] When adding a container: it builds on Docker Hub and can be pulled.
- [x] The filenames in the "images" section are unique (to avoid appliances and/or versions overwriting each other).
- [ ] If you forked the repo, running check.py doesn't drop any errors for the new file.
- [x] *Optional: a symbol has been created for the new appliance.*

### CODE REVIEW

**Comment by mininetworks** [comment]
Sorry. I will check by check.py by myself. And pull request again when all will be fine.

**Comment by adosztal** [comment]
Please replace the download URLs to official ones. Due to legal reasons, we can't allow 3rd party download sites.

**Comment by adosztal** [comment]
Btw what does this "Huawei eNSP + magic" mean? Did you change the official image to make it available outside of eNSP?

**Comment by grossmj** [comment]
Indeed, I am not aware that Huawei has released images that can be run with Qemu.

**Comment by mininetworks** [comment]
The appliances are based on official Windows 7 Professional and require license. There is official eNSP inside and free soft (TCP_COM,  snort, ubridge) that exposes console and interfaces to GNS3.

**Comment by mininetworks** [comment]
We will fix all the issues and come back next time

**Pull request closed without merging**
