### PR TITLE
Add StoneWork mini

### PR DESCRIPTION
**Pull request by juliusmilan**
Before submitting a pull request, please check the following.

---
When updating an **existing** appliance:
- [ ] The new version is on top.
- [ ] The filenames in the "images" section are unique, to avoid appliances / version overwriting each other.
- [ ] If you forked the repo, running check.py doesn't drop any errors for the updated file.
---
When creating a **new** appliance:
- It's tested locally, i.e.
  - [Y] You dragged an instance into a project on your box, got it installed (if necessary), and did some basic network checks (ping, UI reachable, etc.).
  - [Y] GNS3 VM can run it without any tweaks.
  - [Y] The device is in the right category: router, switch, guest (hosts), firewall
  - [Y] You filled in as much info as possible (checks the schemas and other appliance files for some guidance).
- [Y] When adding a container: it builds on Docker Hub and can be pulled.
- [Y] The filenames in the "images" section are unique (to avoid appliances and/or versions overwriting each other).
- [Y] If you forked the repo, running check.py doesn't drop any errors for the new file.
- [Y] *Optional: a symbol has been created for the new appliance.*

### CODE REVIEW

**Comment by grossmj** [comment]
Thanks :+1:

**Comment by grossmj** [comment]
No worries :) We have a sync with the gns3-registry, your appliance should automatically be added in the next few days. I am going to confirm that delay with our webmasters.

**Comment by juliusmilan** [comment]
Thanks a lot Jeremy and sorry for having stupid questions :) but now I have one more, forwarded from the sales.
I can see description of my image ("StoneWork is VPP and Ligato based routing platform") here:
https://gns3.com/marketplace/appliances/stonework
but cannot see it here:
https://www.gns3.com/initiatives/stonework

Why is that? Can I do anything in order to get it there as well? I didn't find myself.

**Comment by grossmj** [comment]
I will check with our webmasters.

**Pull request merged**
