### PR TITLE
Availability

### PR DESCRIPTION
**Pull request by adosztal**
Merge whenever you'd like to; I keep the content up to date in both branches.

### CODE REVIEW

**Comment by noplay** [comment]
I think I have a solution. We can update the schema and remove all the:
```
"additionalProperties": false,
```

This will allow us to add key in files without creating a validation error and avoiding the need to ship new client version if we want to add more informations in the file.

We will ship this schema with 1.5.3 and 2.0.0

Also we should bump the registry_version to 4 in order to have old client displaying an error message you need to upgrade GNS3 in order to read this file instead of a crash.

What do you think of that?

**Comment by adosztal** [comment]
Sounds good; done.

**Comment by adosztal** [comment]
Ok, I don't know how to resolve this conflict. I caused it by accidentally pulling the upstream master to the availability branch. Then I received this:
```
Auto-merging appliances/mikrotik-chr.gns3a
CONFLICT (content): Merge conflict in appliances/mikrotik-chr.gns3a
Auto-merging appliances/forticache.gns3a
CONFLICT (add/add): Merge conflict in appliances/forticache.gns3a
Automatic merge failed; fix conflicts and then commit the result.
```
I reverted to commit d1bc12a by issuing "git reset --hard d1bc12a", then issued "git push origin availability", but the conflict is still there. @noplay, can you resolve it?

**Comment by noplay** [comment]
I try to squash everything in a single commit and rebase it:
https://github.com/GNS3/gns3-registry/tree/availability

**Comment by adosztal** [comment]
What if I close this PR and open a new one? My local branch isn't corrupted.

**Comment by noplay** [comment]
Yeah you can do that

**Comment by adosztal** [comment]
Closing for reopening. :)

**Pull request closed without merging**
