### PR TITLE
Add centos appliance / Network automation container with Pycharm

### PR DESCRIPTION
**Pull request by AJNOURI**
Add centos appliance from osboxes.org
demo: https://www.youtube.com/watch?v=8icRLRL1ODQ
Network automation container with Pycharm
demo: https://www.youtube.com/watch?v=vCYymQzxYi8

### CODE REVIEW

**Comment by AJNOURI** [comment]
The validator is complaining about "spice" as a console type, though it is on the list of qemu console type:

image

**Comment by ehlers** [comment]
First of all you set the registry_version to 3, that means the appliance is compatible with GNS3 1.5, registry version 4 is for GNS3 2.0. Both don't support spice, because it doesn't exist in these GNS3 versions.

About a month ago Jeremy added the spice console type to GNS3 2.1, but not to the registry.
@grossmj should either create registry version 5 with just the spice addition, or add spice to registry version 4 and accept, that appliances using spice will fail during import into GNS3 2.0.

In any case, if you keep spice, you will be incompatible with GNS3 2.0. Therefore all the other appliances are still using vnc.

**Comment by AJNOURI** [comment]
Thanks @ehlers for the clarifications.
I have tried to make it work with vnc, but without success. The only combination that worked for vmdk image unchanged* is:
-vga qxl  & spice

**Comment by ehlers** [comment]
Well, the idea is to use the lowest registry version without loosing functionality. When spice is needed, you have to use the registry version that supports it. So you have to wait, in which registry version Jeremy will implements spice.

**Comment by AJNOURI** [comment]
In this case, if it is possible @grossmj could check & merge only the second commit, I'll wait for 1st until new registry version. 
Users can download the file apart and install the appliance.

**Comment by grossmj** [comment]
Thanks :+1:

**Comment by AJNOURI** [comment]
Thanks Jeremy!

2017-10-26 10:30 GMT+02:00 Jeremy Grossmann <notifications@github.com>:

**Pull request merged**
