### PR TITLE
Fix check.py with feedbacks from @ehlers

### LINKED ISSUE #43: check.py: Multiprocessing doesn't correctly handle errors and sys.exit
In line 37 ```urllib.request.urlopen(req, 5)``` should be changed to ```urllib.request.urlopen(req, timeout=5)```. Furthermore a timeout raises an urllib.error.URLError exception, what gives a wrong error message.

This got undetected because all unhandled exceptions within check_url are not shown. Furthermore an sys.exit within check_url (on an handled exception) leads to a non-ending check.py.

With the following patch, I changed the easily solvable problems. But now a bad URL doesn't stop check.py, the error message can easily be missed. And the unhandled exception problem is not solved.

```
diff --git a/check.py b/check.py
index e10ceba..dd547ec 100644
--- a/check.py
+++ b/check.py
@@ -34,14 +34,14 @@ def check_url(url, appliance):
     try:
         print("Check " + url)
         req = urllib.request.Request(url, method='HEAD')
-        urllib.request.urlopen(req, 5)
+        urllib.request.urlopen(req, timeout=5)
     except urllib.error.HTTPError as err:
         if err.getcode() >= 400:
             print('Error with url ' + url + ' - ' + str(err))
-            sys.exit(1)
-    except urllib.error.URLError:
-        print('Invalid URL ' + url)
-        sys.exit(1)
+#            sys.exit(1)
+    except urllib.error.URLError as err:
+        print('Error with url ' + url + ' - ' + str(err))
+#        sys.exit(1)
 
 
 def check_appliance(appliance):
```

### PR DESCRIPTION
**Pull request by noplay**
Fix #43 

@ehlers what did you think about that?

### CODE REVIEW

**Comment by ehlers** [comment]
While check.py looks fine now, but I'm not really able to use it. Quite often I'm getting errors on the URL check.

One notorious difficult URL was https://www.juniper.net (timeout), after changing it to https://www.juniper.net/us/en/ that problem went away. Later https://www.juniper.net works again.

Just I had problems with http://downloads.sourceforge.net, now it's OK again.

When I repeat check.py several times a always get a "Remote end closed connection without response" from https://supportcenter.checkpoint.com/supportcenter/portal?eventSubmit_doGoviewsolutiondetails=&solutionid=sk104859 , even when I retry it in my browser. As that was not a "normal" http error, it was tricky to get. I have to add the url to the exceptions string to get it.

```
diff --git a/check.py b/check.py
index bc7d8fc..267ae58 100644
--- a/check.py
+++ b/check.py
@@ -44,6 +44,8 @@ def check_url(args):
         raise Exception('Invalid URL ' + url)
     except socket.timeout as e:
         raise Exception('Timeout URL ' + url)
+    except Exception as e:
+        raise Exception(url + ' - ' + str(e))


 def check_appliance(appliance):
```

I get these errors also, when I do these checks with a tiny python script, that does only one URL check (with multitasking). So it's not the fault of check.py. I don't know, if my internet router is so flaky, normally I don't have problems.

Because of all those false positives I currently would move the URL check out of check.py into a separate program, that checks all URL and creates a list of non-working URLs, that should be checked manually. This URL-check-script should not end on the first error.

To summerize, check.py is fine, but I can't use it on my internet access.

**Comment by noplay** [comment]
The worse. It's well know compagnies that create issues...

**Comment by noplay** [comment]
I improved it with retry and split the check in two tools.

**Comment by ehlers** [comment]
That looks really good!!!

It's a shame, that some web sites make it that difficult that check their existence. But that's something we can't change. Under this condition your solution is the best, we can deliver. A quick check against our own errors and a longer check for these pesky URLs.

**Comment by noplay** [comment]
Thanks for feedbacks

**Pull request merged**
