### PR TITLE
Add truenas

### PR DESCRIPTION
**Pull request by scls19fr**
Before submitting a pull request, please check the following.

Untested new appliance.
Helps #915 

---
When updating an **existing** appliance:
- [ ] The new version is on top.
- [ ] The filenames in the "images" section are unique, to avoid appliances / version overwriting each other.
- [ ] If you forked the repo, running check.py doesn't drop any errors for the updated file.
---
When creating a **new** appliance:
- It's tested locally, i.e.
  - [ ] You dragged an instance into a project on your box, got it installed (if necessary), and did some basic network checks (ping, UI reachable, etc.).
  - [ ] GNS3 VM can run it without any tweaks.
  - [ ] The device is in the right category: router, switch, guest (hosts), firewall
  - [ ] You filled in as much info as possible (checks the schemas and other appliance files for some guidance).
- [ ] When adding a container: it builds on Docker Hub and can be pulled.
- [ ] The filenames in the "images" section are unique (to avoid appliances and/or versions overwriting each other).
- [ ] If you forked the repo, running check.py doesn't drop any errors for the new file.
- [ ] *Optional: a symbol has been created for the new appliance.*

### CODE REVIEW

**Comment by grossmj** [comment]
Awesome, I will review soon. Thanks a lot :+1:

**Comment by scls19fr** [comment]
GNS3 appliance for TrueNAS CORE raises a Python exception on console when installing. See 
TrueNAS CORE install pb
Unfortunately I can't know what was before "124"

On the other side, TrueNAS SCALE doesn't face such a problem. I have been able to see web interface and log in. I haven't test more.

**Comment by grossmj** [comment]
I managed to install TrueNAS CORE without any issue. Looks like your appliance couldn't connect somewhere.

Screenshot from 2024-09-23 14-25-01

Screenshot from 2024-09-23 14-27-46

**Comment by grossmj** [comment]
I was also able to install the TrueNAS SCALE but I had to select the Legacy BIOS option. Maybe that's something to add in the `usage` field similar to https://github.com/GNS3/gns3-registry/blob/master/appliances/asterisk.gns3a#L15?

Screenshot from 2024-09-23 14-38-12

**Pull request merged**
