### PR TITLE
Use Xorg for tinycore appliances

### PR DESCRIPTION
**Pull request by noplay**
This use the tips from @ehlers allowing a better sync
between mouse pointer and VNC client.

### CODE REVIEW

**Comment by ehlers** [comment]
Funny, just in the morning I had one additional idea, to make it easier to change the keyboard layout.

```
cat > 98-keyboard.conf <<'EOF'
Section "InputClass"
	Identifier "keyboard"
	MatchIsKeyboard "on"
	Option "xkb_layout" "us"
	Option "xkb_variant" "nodeadkeys"
EndSection
EOF
sudo mv 98-keyboard.conf /usr/local/share/X11/xorg.conf.d/
```

Furthermore add these links to make it easier to edit the Xorg config file:
```
ln -s /usr/local/share/X11/xorg.conf.d/98-keyboard.conf keyboard.conf
ln -s /usr/local/share/X11/xorg.conf.d/99-resolution.conf resolution.conf
```

Hopefully I haven't made typing errors, the keyboad.conf is tested and added by cut-and-paste.

**Comment by noplay** [comment]
How can we inform the user about how to change the keyboard layout?

Another solution perhaps is too add an X tools to change the keyboard.

Due to the fact I'm french it's something also usefull for me :P

**Comment by ehlers** [comment]
One more:
Is 800x600 a good resolution for firefox ? For ostinato it is fine, I choosed the minimum acceptable resolution to give people with small screens the possibility to use it. But I don't know for firefox.

**Comment by ehlers** [comment]
I just added the instruction how to add the resolution in the web page about ostinato. But agreed, I tool would be much nicer. It doesn't even have to be a GUI, a simple terminal based script should do it as well.

**Comment by ehlers** [comment]
If you have some time I would create a dialog based script to setup the resolution and keyboard layout. I'm just busy doing other stuff. But you can do that as well, should be easy. The more interesting stuff is, how to place this script in the GUI menu system.

**Comment by noplay** [comment]
800x600 work on my mac :P The only web site not working is gns3.com :P 

Current screen resolution by percentage users in the last days:
devices_-_google_analytics

Increasing the resolution to 1024x768 mean 1% of users will have trouble

**Comment by noplay** [comment]
A graphical tool exist for resolution:
http://forum.tinycorelinux.net/index.php?topic=3859.0

**Comment by ehlers** [comment]
Just a rough setup tool for the keyboard layout:

select_kbd ist a simple dialog based script, I "stole" the list of keyboards from debian. You have to instal dialog (tce-load -wi dialog).
[select_kbd.txt](https://github.com/GNS3/gns3-registry/files/86082/select_kbd.txt)

And this is a simple desktop integration, I still need a good icon.
[keyboard.desktop.txt](https://github.com/GNS3/gns3-registry/files/86084/keyboard.desktop.txt)

**Comment by ehlers** [comment]
Haven't thought about Xdialog, should look nicer (I hope) and it should be easy to change the script from dialog to Xdialog.

What do you think about this? Will you / shall I invest some time to polish it? Or do you have another idea?

**Comment by noplay** [comment]
I think with xdialog it will be great

**Comment by noplay** [comment]
Do you know where I should put the desktop file?

**Comment by ehlers** [comment]
/usr/local/share/applications

**Comment by ehlers** [comment]
Had another look in my select_kbd script. I noticed, that the save (file tool.sh -b) should be done always after the sed command. Then it will be saved, no matter if the reload is requested or not.

The other point is the reload, it would be enough to restart X, but that seems not so easy. After some head scratching I got the following idea: ```sh -c 'killall Xorg; sleep 2; startx </dev/tty1 >/dev/tty1 2>&1' &```

**Comment by ehlers** [comment]
I've created an update, see https://github.com/ehlers/gns3-registry/commit/4c3dcab4fc8ae19fa1e3582cd914266d19c1150f

It includes a keyboard layout setup tool, which is integrated into the desktop. To activate the new setting only the GUI restarts (after confirmation), the OS doesn't reboot.
screenshot_tinycore-linux

To copy the icon from the packer directory into the VM, I added the http option into the boot command line.

Now I see three more tasks:
- Julien reviews my changes. I have no idea how to integrate them into this PR.
- X doesn't start with the 99-resolution.conf with the default cirrus video card. Maybe it's possible that it works with both "std" and "cirrus".
- GUI tool to change the resolution, either lxrandr or a similar tool like the keyboard tool.

**Comment by ehlers** [comment]
Another one: https://github.com/ehlers/gns3-registry/commit/dbb954e43a755d4fcdfe009ccd3876cd9e4785d2

This adds a screen resolution tool. I tried xrandr/lxrandr but I got these tools only to change the physical screen size, the virtual screen size wasn't changed. Therefore I took the setup_keyboard tool as a base and created a resolution tool. Now both screen sizes (physical and virtual) are changed.

I got it to work also without "vga=std" (cirrus video card), I just removed the DefaultDepth line in the config file

**Comment by noplay** [comment]
Thanks it's work I'm working on merging stuff and pushing images

**Comment by ehlers** [comment]
Just as an idea:

The guy.sh got rather big, maybe the scripts (setup_resolution and setup_keyboard) can be moved to the html/gui directory, just as the icons and then loaded into the image with wget.

On the other side having one file, where everything is included is also a nice feature.

It's your choice :-)

**Comment by noplay** [comment]
Finally merged! Thanks a lot for the help

**Pull request merged**
