### PR TITLE
New appliance version for Firepower 6.3.0.  Re-order list to comply with new standard.

### PR DESCRIPTION
**Pull request by parkerbrother1**
Before submitting a pull request, please check the following.

---
When updating an **existing** appliance:
- [x] The new version is on top.
- [x] The filenames in the "images" section are unique, to avoid appliances / version overwriting each other.
- [x] If you forked the repo, running check.py doesn't drop any errors for the updated file.
---
When creating a **new** appliance:
- It's tested locally, i.e.
  - [ ] You dragged an instance into a project on your box, got it installed (if necessary), and did some basic network checks (ping, UI reachable, etc.).
  - [ ] GNS3 VM can run it without any tweaks.
  - [ ] The device is in the right category: router, switch, guest (hosts), firewall
  - [ ] You filled in as much info as possible (checks the schemas and other appliance files for some guidance).
- [ ] When adding a container: it builds on Docker Hub and can be pulled.
- [ ] The filenames in the "images" section are unique (to avoid appliances and/or versions overwriting each other).
- [ ] If you forked the repo, running check.py doesn't drop any errors for the new file.
- [ ] *Optional: a symbol has been created for the new appliance.*

### CODE REVIEW

**Comment by grossmj** [comment]
I am confused, why is this PR closed?

**Comment by adosztal** [comment]
Oops, didn't notice that, just reviewed the files. @parkerbrother1, why did you close the PR before it got merged?

**Comment by grossmj** [comment]
@parkerbrother1 ping?

**Comment by grossmj** [comment]
Sorry please ignore our last messages, I guess there was some kind of confusion. Your appliances have already been committed: https://github.com/GNS3/gns3-registry/commit/125f2ad67d1e18cf1e28dde245824a991c32f6b7

**Pull request closed without merging**
