### PR TITLE
First draft cisco-nxosv9k.gns3a

### PR DESCRIPTION
**Pull request by gns3madman**
First Draft of a .gns3a appliance for the Cisco Nexus 9000v vm

### CODE REVIEW

**Comment by noplay** [comment]
Related to https://github.com/GNS3/gns3-vm/issues/88

Thanks a lot for the contribution we have a proper support for bios that will be include in 2.0 and that will allow us to ship bios image with GNS3 this will allow an easy install.

I keep PR open for the moment in order to allow everyone to use it. We could improve it when the 2.0.0 beta 2 will be available.

**Comment by grossmj** [comment]
SATA support will speed up NX-OSv 9000 booting: https://github.com/GNS3/gns3-gui/issues/1749

**Comment by jean-christophe-manciot** [comment]
@grossmj @noplay 
I am able to boot a nx-osv-9k, configure it properly, save the running-config, but when I reboot it, it fails into the "loader >" prompt.
Is anyone able to reboot correctly a nx-osv-9k within GNS3?

**Comment by gns3madman** [comment]
jean-christophe-manciot,

From the cisco documentation:

NX-OSv 9000 has the following guidelines and limitations:

• After initial setup of the NX-OSv 9000, you must configure the booting image in your system. Otherwise, the NX-OSv 9000 drops to the loader> prompt after reload/shut down.

switch# configure terminal
switch(config)# boot nxos n9000-dk9.7.0.3.I2.0.454.bin
switch(config)# copy running-config startup-config

In America, we have a saying for things like this: "Are you freaking kidding me?"

**Comment by jean-christophe-manciot** [comment]
Thanks @gns3madman 
> In America, we have a saying for things like this: "Are you freaking kidding me?"

:-) You're right, My bad: I should have seen this. 
However, it would be clearer to put that crucial information within the correct paragraph ("NX-OSv 9000 Installation/Deployment" or "NX-OSv 9000 Configuration").
FYI, the correct command is:
```
switch(config)# boot nxos bootflash:nxos.7.0.3.I5.1.bin
Performing image verification and compatibility check, please wait....
switch(config)# 
```
Eluding the bootflash file system information confuses NX-OS even though:
```
switch(config)# pwd
bootflash:
```

**Comment by adosztal** [comment]
I think this can be closed, the one in the repo is more up to date.

**Comment by noplay** [comment]
Thanks to everyone

**Pull request closed without merging**
