### PR TITLE
Update Ostinato appliance with official images

### PR DESCRIPTION
**Pull request by pstavirs**
Update Ostinato appliance with official images

 * This appliance is now maintained by Srivats P (@pstavirs)
 * Points to official Ostinato image(s) for GNS3 (requires payment)

Thanks to Bernhard Ehlers (@b-ehlers) for creating and maintaining this appliance till date.

@grossmj Are all the icons in `/symbols` not packaged along with the GNS3 image? I couldn't find `symbols/ostinato-3d-icon.svg` in the GNS3 VM image. Is GNS3 moving to the https://github.com/ecceman/affinity iconset?

### CODE REVIEW

**Comment by grossmj** [comment]
> @grossmj Are all the icons in /symbols not packaged along with the GNS3 image? I couldn't find symbols/ostinato-3d-icon.svg in the GNS3 VM image.

Custom icons are saved there: https://github.com/GNS3/gns3-registry/tree/master/symbols and the symbol is downloaded and pushed to the server when the appliance is installed. I am not totally satisfied with this and will check how we can improve.

> Is GNS3 moving to the ecceman/affinity iconset?

Yes, our goal is to use affinity symbols by default our next major version, GNS3 v3.0

**Comment by pstavirs** [comment]
@grossmj I have changed the Ostinato appliance default icon to one from the affinity set. I will leave the custom Ostinato icon here for now. Should I remove the Ostinato related packer files as well?

**Comment by grossmj** [comment]
> Should I remove the Ostinato related packer files as well?

Yes please 👍

**Comment by pstavirs** [comment]
@grossmj All changes are done. You may merge at your convenience.

**Comment by grossmj** [comment]
Looks great, thanks a lot! 👍

**Pull request merged**
