### PR TITLE
Updating AlmaLinux and RockyLinux to version 8.5

### PR DESCRIPTION
**Pull request by Da-Geek**
---
When updating an **existing** appliance:
- [X] The new version is on top.
- [X] The filenames in the "images" section are unique, to avoid appliances / version overwriting each other.
- [X] If you forked the repo, running check.py doesn't drop any errors for the updated file.
---

AlmaLinux only has version 8.5 available from the download URL

### CODE REVIEW

**Comment by Da-Geek** [comment]
Anything I need to do to push this PR forward?

**Comment by grossmj** [comment]
> Anything I need to do to push this PR forward?

No all good, thanks a lot 👍

**Comment by Da-Geek** [comment]
> > Anything I need to do to push this PR forward?
> 
> No all good, thanks a lot 👍

@grossmj 
I have quiet a few more tiny little updates that I wish to make (like adding the correct logo/icons) as well as some bigger
changes, like adding some more Official GUI Based Linux Images for Fedora/CentOS, openSUSE and Ubuntu.
I prefer to do these sort of changes as smaller PRs dedicated to the task, rather than a BIG single change with a bunch of
changes all at once.
So if it is OK to do so, I will continue to create PRs against the repo?

**Comment by grossmj** [comment]
> So if it is OK to do so, I will continue to create PRs against the repo?

Yes, no worries. I also prefer smaller PRs dedicated to the task.Thanks again 👍

**Pull request merged**
