### PR TITLE
FortiGate appliance

### PR DESCRIPTION
**Pull request by adosztal**
5.4.0 has not been added yet because only an update package is available to download. Will check later.

### CODE REVIEW

**Comment by adosztal** [comment]
Oops, made a typo at R54C17, will correct it soon.

**Comment by noplay** [comment]
You need to remove direct_download_url it's only when you have a link to the file. One day we hope to auto download images for open source appliances.

Thanks a lot for the contribution

**Comment by noplay** [comment]
For the the filename: *fortios.qcow2* . Is it possible to have something more unique? Ideally the original filenane if it contain the version number. Otherwise just add the version number it allow to have multiple version installed.

**Comment by adosztal** [comment]
Direct link is removed.

Downloaded filename is FGT_VM64_KVM-v5-build0701-FORTINET.out.kvm.zip; when I unzip it, I get fortios.qcow2. Should I put the archive's name there?

**Comment by noplay** [comment]
I propose FGT_VM64_KVM-v5-build0701-FORTINET.out.kvm.qcow2 it will help people to found the file on disk and in their network share

**Comment by adosztal** [comment]
Can I get some help on the Travis CI build output? I don't see where the issue is.

**Comment by noplay** [comment]
Sorry I just merged it this morning.

Add a line in the qemu block:
```json
"kvm": "require"
```

Or:
```json
"kvm": "allow"
```

This will chose if in 1.4.1 you can use the VM without KVM or if KVM is mandatory. We make KVM mandatory when the VM is too slow to run without it.

**Comment by adosztal** [comment]
I added "kvm: allow" for now, will check performance without it.

**Comment by noplay** [comment]
Oh yes or you can ignore it.

**Comment by noplay** [comment]
I just add a check for travis in order to check the boot_priority

**Comment by adosztal** [comment]
I was thinking we should make the empty images like this:
> "filename": "fortigate_empty30G.qcow2"

Instead of this:
> "filename": "empty30G.qcow2"

Otherwise one appliance might overwrite another's disk image. Am I right or missing the point somewhere?

**Comment by noplay** [comment]
No we can keep empty30G.qcow2 because when the appliance start it create an
overlay disk this mean all appliances can share the same empty disk.

**Comment by noplay** [comment]
It's a feature of qcow2

**Comment by adosztal** [comment]
Gotcha. The appliance is ready then. :)

**Comment by noplay** [comment]
Merged it will be in the marketplace soon.

**Comment by noplay** [comment]
https://gns3.com/marketplace/appliance/fortigate

**Pull request merged**
