### PR TITLE
New Cisco CSR1000V version

### PR DESCRIPTION
**Pull request by adosztal**
3.17.1S

### CODE REVIEW

**Comment by noplay** [comment]
It seem we have a conflict with current master branch

**Comment by adosztal** [comment]
Is it because I renamed the existing version too? 3.16 was not exact so I changed it to 3.16.0S.

**Comment by noplay** [comment]
I think it's because last VIRL images was added a few day ago

**Comment by adosztal** [comment]
Oh, I see now. And that's 3.17 too. I close this pull request then.

**Pull request closed without merging**
