### PR TITLE
Docker Router symbols

### PR DESCRIPTION
**Pull request by AJNOURI**
Hi @noplay.  A couple of Docker router symbols.

### CODE REVIEW

**Comment by noplay** [comment]
Nice idea

With which tool did you export the SVG? They seem to have been exported as
a bitmap.

**Comment by AJNOURI** [comment]
The router itself is a blender object rendered into png, edited with Inkscape (docker logo mapped) and saved into SVG.

**Comment by noplay** [comment]
I suggest to edit the GNS3 router file with inkscape and change the color on it. You will already have the correct size (no need for the convert tool) and the export will be cleaner without aliasing effect.

**Comment by AJNOURI** [comment]
OK.

**Comment by noplay** [comment]
Nice.

I will fix the licence detail with mention to docker and merge

**Pull request merged**
