### PR TITLE
New appliance: Dell FTOS

### PR DESCRIPTION
**Pull request by adosztal**

### CODE REVIEW

**Comment by noplay** [comment]
I'm not sure if we can provide this direct download urls. Is it Dell urls?

**Comment by adosztal** [comment]
I took it out just to be on the safe side.

**Comment by noplay** [comment]
Beware of git issue I squashed the commit to a single one.

**Comment by noplay** [comment]
https://gns3.com/discussions/new-appliance-supported-dell-fto

**Pull request merged**
