### PR TITLE
Added full version of Win10 

### PR DESCRIPTION
**Pull request by cyberpunk2350**
Before submitting a pull request, please check the following.

---
When updating an **existing** appliance:
- [X] The new version is on top.
- [X] The filenames in the "images" section are unique, to avoid appliances / version overwriting each other.
- [X] If you forked the repo, running check.py doesn't drop any errors for the updated file.
---
When creating a **new** appliance:
- It's tested locally, i.e.
  - [x] You dragged an instance into a project on your box, got it installed (if necessary), and did some basic network checks (ping, UI reachable, etc.).
  - [x] GNS3 VM can run it without any tweaks.
  - [x] The device is in the right category: router, switch, guest (hosts), firewall
  - [x] You filled in as much info as possible (checks the schemas and other appliance files for some guidance).
- [x] When adding a container: it builds on Docker Hub and can be pulled.
- [x] The filenames in the "images" section are unique (to avoid appliances and/or versions overwriting each other).
- [x] If you forked the repo, running check.py doesn't drop any errors for the new file.
- [x] *Optional: a symbol has been created for the new appliance.*

### CODE REVIEW

**Comment by cyberpunk2350** [comment]
Added the full version of Win10 vs just the preview version.

**Comment by cyberpunk2350** [comment]
Also added the qemu option "-usbdevice tablet" to the Windows Server template to eliminate the drifting/unsync'd mouse in tightvnc

**Comment by WarpRat** [comment]
Ha, I was just coming here to see if anyone had submitted a pull request for this yet and here it is, nice.

**Comment by grossmj** [comment]
Thanks a lot.

**Pull request merged**
