### PR TITLE
Check different version of the appliance schema

### PR DESCRIPTION
**Pull request by noplay**
This support only registry version 3 & 4 in order to be use for #232

It's also test if we can downgrade an appliance

### CODE REVIEW

**Comment by adosztal** [comment]
The appliance_v3.json file contains v4 properties (bios image, sata drive, cpus) too.

**Comment by noplay** [comment]
Hmm do you know wich git commit mark the end of version 3 appliance file? (It's the shame I didn't tag it)

**Comment by adosztal** [comment]
The v4 was introduced in https://github.com/GNS3/gns3-registry/commit/686dc59a39dbd149035bd8f857fb9033332bc32b, however there are commits before this that should be in v4. In addition to the above, "availablility" is also a v4 property.

There are no others I remember of.

**Comment by adosztal** [comment]
Also, appliance_v3.json contains "linked_base" instead of "linked_clone".

**Comment by adosztal** [comment]
Is https://github.com/GNS3/gns3-registry/commit/51ae9179465dd3b11db561e41c2beff5750fb5f5#diff-2fca04a5772bc5b644e3ebc8ba85f401 handled in 1.5?

**Comment by noplay** [comment]
No it's a V4 property I think

**Comment by adosztal** [comment]
What about https://github.com/GNS3/gns3-registry/commit/5d626e0095d90d754f3865fcb5886019fac15346?

**Comment by ehlers** [comment]
Why not copy the appliance.json from GNS3 v1.5?
https://github.com/GNS3/gns3-gui/blob/1.5/gns3/schemas/appliance.json

**Comment by adosztal** [comment]
Oh my, how could we forget that one? :)
Great idea!

**Comment by noplay** [comment]
PR updated

**Comment by ehlers** [comment]
The appliance.json in GNS3 GUI v2.0 differs from appliance_v4.json. In the GNS3 GUI it uses linked_base while here it uses linked_clone (since 45852eccfa47df1df2148c6a73bdfefcc3eff3d5).

I suggest to set appliance_v4.json to the version distributed with GNS3 v2.0 and start a new version 5, that gets frozen with GNS3 v2.1.

**Comment by ehlers** [comment]
As no appliance uses linked_base nor link_clone, maybe we could stay with v4 and update the schema in GNS3 v2.0.x

**Comment by adosztal** [comment]
Yes, v4 should be linked_clone, v3 can be kept as linked_base but the latter doesn't really matter.

**Comment by noplay** [comment]
Yeah nobody was using this properties.  It was more a bug

**Pull request merged**
