### PR TITLE
Added 2 Brocade devices

### PR DESCRIPTION
**Pull request by adosztal**
All devices & versions have been tested locally, they work fine.
Commit addresses #42

### CODE REVIEW

**Comment by grossmj** [comment]
:+1:

**Comment by adosztal** [comment]
Thanks.
@noplay, could you add them to the Marketplace?

**Comment by noplay** [comment]
I'm on it

**Comment by noplay** [comment]
And voilà :)
https://gns3.com/discussions/new-appliance-supported-brocade-

Thanks a lot

**Pull request merged**
