### PR TITLE
Added Cisco NX-OSv9k & Python containers

### PR DESCRIPTION
**Pull request by adosztal**
I've tested all 3 versions with the new bios image and the sata disk interface. They run well, boot time has been reduced significantly.

### CODE REVIEW

**Comment by adosztal** [comment]
2.x exclusive! Maybe it should be highlighted on the Marketplace.

**Comment by cioby23** [comment]
The latest version nxosv-final.7.0.3.I6.1.qcow2 boots up with only 4GB of RAM. This is the minimum requirement.
http://www.cisco.com/c/en/us/td/docs/switches/datacenter/nexus9000/sw/7-x/nx-osv/configuration/guide/b_NX-OSv_9000/b_NX-OSv_chapter_01.html#concept_C76C3764E39D449A86A4A50D1021306E

**Comment by adosztal** [comment]
Thanks for the head up!

But the I5 ones still require 8G, right?
If yes, I think we should drop them. If no, I simply change the RAM to 4G.

**Comment by noplay** [comment]
We could set the minimum to 4 and leave a note in the description.

**Pull request merged**
