### PR TITLE
Security Onion Appliance

### PR DESCRIPTION
**Pull request by brentstewart**
I'm a noob at Github, so not sure if I'm doing this right.  I'm proposing two files: a security onion appliance and an icon.  I've tested these locally and they seem good.  I think security onion will be interesting to the security folks - lots of good tools.

### CODE REVIEW

**Comment by grossmj** [comment]
Hi, thanks for contributing! Everything looks good excepting the securityonion-logo.png file should be in the "symbols" directory, not in "appliances".

Thanks!

**Comment by grossmj** [comment]
Also, I forgot to ask what is the `SecOnion` file for?

**Comment by brentstewart** [comment]
Yeah, sorry, as I mentioned I'm figuring out Github by trial and error.
1) I have deleted SecOnion.  It was just a file I created trying to figure out uploading.
2) I have moved securityonion-logo.png to symbols.

**Comment by grossmj** [comment]
Almost there however the PR still has securityonion-logo.png in the appliances directory. Maybe the easiest is to delete this file and add it back to the symbols directory?

Don't worry, it takes some practise to figure out GitHub ;) Thanks!

**Comment by brentstewart** [comment]
I think I've got it this time.  Can you take a look?

**Comment by grossmj** [comment]
All good now. Thanks :)

**Comment by grossmj** [comment]
Added to the marketplace: https://gns3.com/marketplace/appliance/security-onion

**Pull request merged**
