### PR TITLE
ontap Simulator template initial release

### PR DESCRIPTION
**Pull request by josephillips85**
Before submitting a pull request, please check the following.

---
When updating an **existing** appliance:
- [ ] The new version is on top.
- [ ] The filenames in the "images" section are unique, to avoid appliances / version overwriting each other.
- [ ] If you forked the repo, running check.py doesn't drop any errors for the updated file.
---
When creating a **new** appliance:
- It's tested locally, i.e.
  - [x] You dragged an instance into a project on your box, got it installed (if necessary), and did some basic network checks (ping, UI reachable, etc.).
  - [x] GNS3 VM can run it without any tweaks.
  - [x] The device is in the right category: router, switch, guest (hosts), firewall
  - [x] You filled in as much info as possible (checks the schemas and other appliance files for some guidance).
- [ ] When adding a container: it builds on Docker Hub and can be pulled.
- [x] The filenames in the "images" section are unique (to avoid appliances and/or versions overwriting each other).
- [x] If you forked the repo, running check.py doesn't drop any errors for the new file.
- [ ] *Optional: a symbol has been created for the new appliance.*

### CODE REVIEW

**Comment by grossmj** [comment]
@josephillips85 where can we download the required images? thanks 👍

**Comment by josephillips85** [comment]
@grossmj  the images can be downloaded from
https://mysupport.netapp.com/site/tools/tool-eula/simulate-ontap/download
You need a account

**Comment by eantowne** [comment]
@josephillips85 - I would recommend using `python3 new_appliance.py` to generate the new appliance file. The one you submitted in the PR seems to be missing an appliance_id as well as few other possible issues that could use refinement. Below are some examples of the items that I noticed.


Normally the download URL is included in the appliance file. Below is an example:

```
"images": [
        {
            "filename": "WinDev2212Eval-disk1.vmdk",
            "version": "2212",
            "md5sum": "c79f393a067b92e01a513a118d455ac8",
            "filesize": 24620493824,
            "download_url": "https://aka.ms/windev_VM_vmware",
            "compression": "zip"
        },
```

- Additionally, "usage" would be good to detail additional information, to include the fact that you need an account to download the image.
- "product_url": "http://www.netapp.com" - This should actually be "vendor_url".
- "documentation_url": "http://www.netapp.com" - https://docs.netapp.com/us-en/ontap-family/ might be better than the vendor homepage URL.

**Comment by josephillips85** [comment]
> @josephillips85 - I would recommend using `python3 new_appliance.py` to generate the new appliance file. The one you submitted in the PR seems to be missing an appliance_id as well as few other possible issues that could use refinement. Below are some examples of the items that I noticed.
> 
> Normally the download URL is included in the appliance file. Below is an example:
> 
> ```
> "images": [
>         {
>             "filename": "WinDev2212Eval-disk1.vmdk",
>             "version": "2212",
>             "md5sum": "c79f393a067b92e01a513a118d455ac8",
>             "filesize": 24620493824,
>             "download_url": "https://aka.ms/windev_VM_vmware",
>             "compression": "zip"
>         },
> ```
> 
> * Additionally, "usage" would be good to detail additional information, to include the fact that you need an account to download the image.
> * "product_url": "http://www.netapp.com" - This should actually be "vendor_url".
> * "documentation_url": "http://www.netapp.com" - https://docs.netapp.com/us-en/ontap-family/ might be better than the vendor homepage URL.

Well im agree with the documentation URL  and im performing the change on a new commit.
Also i guess at this point recreate the template with the python file will going to take more time that i was expecting to do this.
i recommend remove the line from the readme file that said
 
"Two way to create a new appliance:
Copy paste a JSON from the appliances directory"

to avoid future new commits people don't copy a json file from the appliance directory


and put on the documentation that account is required is complete overkill  if you will going to test something  with the most of appliance here required a account to download Ex. Checkpoint , F5 Juniper even cisco

**Comment by josephillips85** [comment]
also i saw the mistake you guys are seeing a very old template file that i upload by mistake please check the commit 
https://github.com/GNS3/gns3-registry/pull/724/commits/502413e35671431e4aa1294c4a6aaf3cba494cad

**Comment by grossmj** [comment]
I have added the missing appliance_id and changed a few other things. I believe it is good to merge now. Please open a new PR if you see anything else. Thanks for your contribution 👍

**Pull request merged**
