### PR TITLE
Proposed Juniper vMX Appliance

### PR DESCRIPTION
**Pull request by gns3madman**
Includes a proposed symbol, and two proposed appliances, one for the Virtual Control Plane (vCP) and one for the Virtual Forwarding Plane (vFP)

### CODE REVIEW

**Comment by noplay** [comment]
@adosztal what do you think of this PR?

**Comment by adosztal** [comment]
I'll check if they comply to Andrew's observations

**Comment by noplay** [comment]
@adosztal did you check or do you need help on that?

**Comment by adosztal** [comment]
Sorry for the delay. They look good. :)

**Comment by noplay** [comment]
Merged I will integrate them on the website

**Comment by noplay** [comment]
I just notice something, the vmx use the .ova files. But ova import is no longer supported in 2.0 because not stable and not use by users. 

They don't provide .qcow or vmdk images?

**Pull request merged**
