### PR TITLE
Added Citrix NetScaler & updated some appliances with new releases

### PR DESCRIPTION
**Pull request by adosztal**
Tested locally, works fine.

### CODE REVIEW

**Comment by noplay** [comment]
https://gns3.com/marketplace/appliance/citrix-netscaler-vpx

**Comment by noplay** [comment]
https://gns3.com/discussions/new-appliance-supported-citrix-n

**Comment by noplay** [comment]
Thanks a lot !

**Comment by jean-christophe-manciot** [comment]
This has nothing to do with GNS3, but have you been able to test the [latest Docker container-based CPX Express](https://www.microloadbalancer.com/)?
I'm experiencing some [weird issue on Ubuntu 16.04 & Docker 1.12.1](http://discussions.citrix.com/topic/380680-cpx-express-cannot-load-it-with-docker/).

**Comment by noplay** [comment]
With docker client I have a working --input options.

When you docker version you have the correct version? Perhaps the client is not correctly updated.

**Pull request merged**
