### PR TITLE
Added VOSS VSP8K switch.

### PR DESCRIPTION
**Pull request by stewilliams-extr**
Added Extreme Networks Virtual Services Platform VSP8K  VOSS

Before submitting a pull request, please check the following.

---
When updating an **existing** appliance:
- [ x] The new version is on top.
- [ x] The filenames in the "images" section are unique, to avoid appliances / version overwriting each other.
- [ x] If you forked the repo, running check.py doesn't drop any errors for the updated file.
---
When creating a **new** appliance:
- It's tested locally, i.e.
  - [x ] You dragged an instance into a project on your box, got it installed (if necessary), and did some basic network checks (ping, UI reachable, etc.).
  - [x ] GNS3 VM can run it without any tweaks.
  - [x ] The device is in the right category: router, switch, guest (hosts), firewall
  - [x ] You filled in as much info as possible (checks the schemas and other appliance files for some guidance).
- [x ] When adding a container: it builds on Docker Hub and can be pulled.
- x[ ] The filenames in the "images" section are unique (to avoid appliances and/or versions overwriting each other).
- [x ] If you forked the repo, running check.py doesn't drop any errors for the new file.
- [x ] *Optional: a symbol has been created for the new appliance.*

### CODE REVIEW

**Comment by grossmj** [comment]
Thanks a lot! I merged it however there is a bug in GNS3 with "boot_priority": "dc", I have opened a bug report: https://github.com/GNS3/gns3-server/issues/1385

**Comment by ehlers** [comment]
While the missing "boot_priority": "dc" should be fixed, for this appliance the boot_priority setting is not needed. Only one disk image (hda) is attached to the VM, so "boot_priority": "c" will do as well. As this is the default, the boot_priority can be removed from this appliance.

**Comment by grossmj** [comment]
Good point, I have removed boot_priority from the appliance :+1:

**Comment by ehlers** [comment]
@grossmj I don't see this appliance in the GNS3 marketplace. Can you please add it?

**Comment by grossmj** [comment]
@ehlers done: https://gns3.com/marketplace/appliance/voss-vm

**Pull request merged**
