### PR TITLE
Ostinato appliance removed - VMs no longer supported

### PR DESCRIPTION
**Pull request by b-ehlers**
In 2016 and 2017 I've added VMs for Ostinato v0.8 and v0.9. These are totally outdated now, v1.0 and v1.1 greatly enhance the user interface and fix several bugs.

At the time v1.0 was released it would be very difficult to create a VM based on tinycore linux as QT5 packages were missing. Therefore I switched to Docker, see <https://www.b-ehlers.de/projects/ostinato4gns3/index.html>. With the release of tinycore linux v11 the QT5 packages were added, so it should be possible to create Ostinato VMs again. But as I'm pleased with the Docker solution I won't do that.

As I no longer want to support these old v0.8/v0.9 VMs I'm going to delete them end of july. I'm not convinced, that Docker appliances are a good idea, so the Ostinato appliance has to go (or someone has to take it over).

### CODE REVIEW

**Comment by grossmj** [comment]
> I'm not convinced, that Docker appliances are a good idea

I was thinking we can create a Docker appliance to replace the VMs but I saw your comment. Why do you think so?

**Comment by b-ehlers** [comment]
> > I'm not convinced, that Docker appliances are a good idea
> 
> I was thinking we can create a Docker appliance to replace the VMs but I saw your comment. Why do you think so?

Issue https://github.com/GNS3/gns3-registry/issues/145: You can update a docker image only by using docker commands in the GNS3VM cli. So normal users are locked to the image they initially download.

**Comment by grossmj** [comment]
> Issue #145  You can update a docker image only by using docker commands in the GNS3VM cli. So normal users are locked to the image they initially download.

Correct, we should do something about this. In the meantime, I may take over the Ostinato appliance. Have you used packer.io to build the old v0.8/v0.9 VMs?

**Comment by b-ehlers** [comment]
> Have you used packer.io to build the old v0.8/v0.9 VMs?

Yes, the packer files are included in this repository: [packer -> tinycore-linux](https://github.com/GNS3/gns3-registry/tree/master/packer/tinycore-linux).

**Comment by b-ehlers** [comment]
VM version removed from the webpage <https://www.b-ehlers.de/projects/ostinato4gns3/index.html>.

**Comment by b-ehlers** [comment]
The developer of Ostinato has created an official [Ostinato for GNS3](https://ostinato.org/pricing/gns3) package. Maybe he can be convinced to add his ostinatostd.gns3a to this registry.

**Comment by grossmj** [comment]
@pstavirs hi, would you be interested? thanks

**Comment by pstavirs** [comment]
@grossmj Happy to take over maintainership of the GNS3 Ostinato appliance. You can discard this pull request - I'll raise a new one next week with the changes in the .gns3a aligning it with the official .gns3a. Users however will need to pay for the official qcow2 image(s) going forward to help support and sustain the Ostinato project. I assume that should be ok as this is the case for Cisco images too (and maybe other vendors?).

I want to thank @b-ehlers for creating and maintaining the Ostinato appliance, supporting both the Ostinato and GNS3 projects and helping out the community at large. Thanks Bernhard!

**Comment by grossmj** [comment]
> Users however will need to pay for the official qcow2 image(s) going forward to help support and sustain the Ostinato project. I assume that should be ok as this is the case for Cisco images too (and maybe other vendors?).

@pstavirs Thanks a lot! No problem, I don't see any issue with this.

**Pull request closed without merging**
