### PR TITLE
A basic DHCP container.

### PR DESCRIPTION
**Pull request by noplay**
This container provide a basic DHCP server that you can drop
in your topology and configure.

### CODE REVIEW

**Comment by noplay** [comment]
Should we host the docker container here or in a dedicated repositories?

**Comment by ehlers** [comment]
For the user, the easiest way is to host the Dockerfiles here and then publish the images at docker hub https://hub.docker.com/explore/ . You can even create automatic builds, see https://docs.docker.com/docker-hub/github/

The docker client then will pull the images from there, if it's not found locally.

**Comment by noplay** [comment]
I pushed gns3/dhcp

**Comment by noplay** [comment]
I will replace it by an automated build if we merge the branch.

**Pull request merged**
