### PR TITLE
asterfusion vAsterNOS

### PR DESCRIPTION
**Pull request by yx464050145**
Before submitting a pull request, please check the following.

---
When updating an **existing** appliance:
- [x] The new version is on top.
- [x] The filenames in the "images" section are unique, to avoid appliances / version overwriting each other.
- [ ] If you forked the repo, running check.py doesn't drop any errors for the updated file.
---
When creating a **new** appliance:
- It's tested locally, i.e.
  - [x] You dragged an instance into a project on your box, got it installed (if necessary), and did some basic network checks (ping, UI reachable, etc.).
  - [x] GNS3 VM can run it without any tweaks.
  - [x] The device is in the right category: router, switch, guest (hosts), firewall
  - [x] You filled in as much info as possible (checks the schemas and other appliance files for some guidance).
- [ ] When adding a container: it builds on Docker Hub and can be pulled.
- [x] The filenames in the "images" section are unique (to avoid appliances and/or versions overwriting each other).
- [ ] If you forked the repo, running check.py doesn't drop any errors for the new file.
- [x] *Optional: a symbol has been created for the new appliance.*

### CODE REVIEW

**Comment by yx464050145** [comment]
update Asterfusion vAsterNOS.gns3a

**Comment by grossmj** [comment]
Thanks for this contribution! 👍 

Screenshot from 2024-04-03 17-28-45

**Comment by yx464050145** [comment]
https://www.gns3.com/marketplace/appliances/asterfusion-vasternos

**Comment by yx464050145** [comment]
We submitted the Asterfusion company login, but it was not displayed in the Marketplace.

**Comment by grossmj** [comment]
> We submitted the Asterfusion company logo, but it was not displayed in the Marketplace.

I have fixed it in https://github.com/GNS3/gns3-registry/pull/870

**Pull request merged**
