### PR TITLE
Add docker/ovs-snmp, a SNMP enabled open vSwitch image source.

### PR DESCRIPTION
**Pull request by d-jsb**
Added a configurable ovs with SNMPd in docker/ 
Created a appliance file.

!!!Open item:  When adding a container: it builds on Docker Hub and can be pulled.

### CODE REVIEW

**Comment by grossmj** [comment]
Thanks 👍

**Comment by d-jsb** [comment]
Hi, just to make sure, will the docker container appear in docker hub "automagically"? Otherwise the appliance file would be broken.

**Comment by grossmj** [comment]
I think I need to trigger the build or manually push the container. There have been changes to Docker Hub and I am not sure if I can do it with their free tier. I am also considering using ghcr.io (GitHub container registry) instead.

**Comment by b-ehlers** [comment]
An overview about the docker subscriptions can be found here: <https://www.docker.com/pricing>.

The main restrictions of the free tier subscription:
* Only 100/200 pulls per 6 hours
* No autobuild, see <https://docs.docker.com/docker-hub/builds/>

Without knowing any details, how GNS3 currently uses the docker registry, I assume these limitations will affect the GNS3 registry.

**Comment by d-jsb** [comment]
> I think I need to trigger the build or manually push the container. There have been changes to Docker Hub and I am not sure if I can do it with their free tier. I am also considering using ghcr.io (GitHub container registry) instead.

I'm sorry, I don't know how such automation works - still learning a lot every day ;)
I believe only the owner of the gns3 dockerhub account will be able to push gns3/ovs-snmp but I think it would be the right place (e.g. better than my personal account I just created)?

**Comment by grossmj** [comment]
No worries, I have access to the GNS3 Docker account and will work on this soon. Thanks 👍

**Comment by grossmj** [comment]
@d-jsb 

I have pushed the image on Docker Hub: https://hub.docker.com/repository/docker/gns3/ovs-snmp

Let me know if you need anything else. Thanks again for your contribution.

**Comment by d-jsb** [comment]
Thanks @grossmj. I pushed a bugfix and opened a MR. I might backport some fixes to the original openvswitch image later :)

**Pull request merged**
